// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwduIRpiQTkVHuWjsbeNKSepu0kQ1pwWQ',
    appId: '1:783291346220:web:55352b0d7074029dd59089',
    messagingSenderId: '783291346220',
    projectId: 'weather-station-iot-a5c40',
    authDomain: 'weather-station-iot-a5c40.firebaseapp.com',
    databaseURL: 'https://weather-station-iot-a5c40-default-rtdb.firebaseio.com',
    storageBucket: 'weather-station-iot-a5c40.firebasestorage.app',
    measurementId: 'G-S1CHFDSGRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQHRFd352SyJ6jOOYNC85K0A6Bfp45ndI',
    appId: '1:783291346220:android:fa0a40813f4ff62ed59089',
    messagingSenderId: '783291346220',
    projectId: 'weather-station-iot-a5c40',
    databaseURL: 'https://weather-station-iot-a5c40-default-rtdb.firebaseio.com',
    storageBucket: 'weather-station-iot-a5c40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDopb7df3c4Xy-OBLYclDl9yg8on33FsD8',
    appId: '1:783291346220:ios:3f1cde82735c82e9d59089',
    messagingSenderId: '783291346220',
    projectId: 'weather-station-iot-a5c40',
    databaseURL: 'https://weather-station-iot-a5c40-default-rtdb.firebaseio.com',
    storageBucket: 'weather-station-iot-a5c40.firebasestorage.app',
    iosBundleId: 'com.example.smartWeatherIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDopb7df3c4Xy-OBLYclDl9yg8on33FsD8',
    appId: '1:783291346220:ios:3f1cde82735c82e9d59089',
    messagingSenderId: '783291346220',
    projectId: 'weather-station-iot-a5c40',
    databaseURL: 'https://weather-station-iot-a5c40-default-rtdb.firebaseio.com',
    storageBucket: 'weather-station-iot-a5c40.firebasestorage.app',
    iosBundleId: 'com.example.smartWeatherIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwduIRpiQTkVHuWjsbeNKSepu0kQ1pwWQ',
    appId: '1:783291346220:web:55352b0d7074029dd59089',
    messagingSenderId: '783291346220',
    projectId: 'weather-station-iot-a5c40',
    authDomain: 'weather-station-iot-a5c40.firebaseapp.com',
    databaseURL: 'https://weather-station-iot-a5c40-default-rtdb.firebaseio.com',
    storageBucket: 'weather-station-iot-a5c40.firebasestorage.app',
    measurementId: 'G-S1CHFDSGRX',
  );

}